// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCawQhygvK9YZ3XfRfTQbEPF6nc9QacZ2Q',
    appId: '1:1067713551412:web:0bf5fc481e87b95b057e61',
    messagingSenderId: '1067713551412',
    projectId: 'todo-a656f',
    authDomain: 'todo-a656f.firebaseapp.com',
    storageBucket: 'todo-a656f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtPWbItxIc3-u8w8rnzbfe1p1r1JnNKrI',
    appId: '1:1067713551412:android:c828e3ca96c32d6a057e61',
    messagingSenderId: '1067713551412',
    projectId: 'todo-a656f',
    storageBucket: 'todo-a656f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC698-ql_hqker6G4eYkzV8jLOZ1w31u3s',
    appId: '1:1067713551412:ios:da201c5e7e06293b057e61',
    messagingSenderId: '1067713551412',
    projectId: 'todo-a656f',
    storageBucket: 'todo-a656f.appspot.com',
    iosBundleId: 'com.example.todo',
  );
}
